### ISSUE TITLE
bug in cuda/python/dist_blockwrapper_pytorch.py

### ISSUE THREAD

**Issue by yeyeleijun** [lepodl/Digital_twin_brain#1]
Line 67-68
`                    if force_rebase or new_base != cortical_subblk_start:
                        subblk_base = (new_base + 1 + overlap - 1) // overlap * overlap`
should be `subblk_base = (new_base  + overlap - 1) // overlap * overlap`

**Comment by lepodl** [comment]
got it, thanks a lot!
