### ISSUE TITLE
bug in generation/make_block.py

### ISSUE THREAD

**Issue by yeyeleijun** [lepodl/Digital_twin_brain#2]
1. Line 219 should be `assert 0 <= s <= e <= k`
2. Line 232 shoule be `assert np.min(degree_max) >= degree`
3. Line 605, delete `for d in dtype:`

**Comment by lepodl** [comment]
> 1. Line 219 should be `assert 0 <= s <= e <= k`
> 2. Line 232 shoule be `assert np.min(degree_max) >= degree`
> 3. Line 605, delete `for d in dtype:`
